<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tribuno.Application\Tribuno.Application.csproj" />
    <ProjectReference Include="..\Tribuno.Domain\Tribuno.Domain.csproj" />
    <ProjectReference Include="..\Tribuno.Kafka\Tribuno.Kafka.csproj" />
  </ItemGroup>

</Project>
